- hosts: all
  tasks:
    - name: test
      template:
        src: resolv.conf.j2
        dest: /tmp/resolv.conf

- hosts: all
  name: block
  tasks:
    - name: block
      block:
      - package:
          name: httpd
          state: present
      - name: test
        service:
          name: httpd
          state: started
          enabled: yes

- hosts: node00
  tasks:
    - name: test
      package:
        name: firewalld
        state: present
    - name: test 
      service:
        name: firewalld
        state: started
    - name: test
      firewalld:
        permanent: true
        immediate: true
        source: 172.20.1.101
        state: enabled
