---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - package:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed
      when: ansible_facts['distribution'] == 'CentOS' 

